version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/woori-zip-BE
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh   # 배포 후 실행할 스크립트
      timeout: 200
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh   # 애플리케이션 시작 스크립트
      timeout: 200
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh    # 애플리케이션 중지 스크립트
      timeout: 200
      runas: root
