version: 0.0
os: linux
files:
  - source: /                           # 모든 파일을 복사
    destination: /home/ubuntu/woori-zip-BE  # EC2 인스턴스 내 Spring Boot 파일의 배포 경로
  - source: /scripts                    # 스크립트 폴더
    destination: /home/ubuntu/woori-zip-BE/scripts

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh   # 배포 후 실행할 스크립트
      timeout: 200
      runas: root
  ApplicationStart:
    - location: scripts/start-server.sh   # 애플리케이션 시작 스크립트
      timeout: 200
      runas: root
  ApplicationStop:
    - location: scripts/stop-server.sh    # 애플리케이션 중지 스크립트
      timeout: 200
      runas: root
